from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import yaml


BASE_DIR = Path(__file__).resolve().parent.parent
CONFIG_PATH = BASE_DIR / "config" / "schools.yaml"
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from crawler.catalog_builder import build_catalog, write_catalog


def load_school_entries() -> list[dict[str, object]]:
    payload = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))
    return payload.get("schools", [])


def main() -> None:
    parser = argparse.ArgumentParser(description="Build per-school JSON shards for all configured schools")
    parser.add_argument(
        "--output-dir",
        default=str(BASE_DIR / "data" / "schools"),
        help="Directory for per-school catalog json files",
    )
    parser.add_argument(
        "--live-output",
        default=str(BASE_DIR / "data" / "live_catalog.json"),
        help="Path for merged live catalog output",
    )
    parser.add_argument(
        "--cache-dir",
        default=str(BASE_DIR / "data" / "cache"),
        help="Cache directory for crawler and enrichment",
    )
    parser.add_argument("--refresh", action="store_true", help="Ignore caches and rebuild from source")
    parser.add_argument("--quiet", action="store_true", help="Disable progress logs")
    parser.add_argument(
        "--teacher-timeout",
        type=float,
        default=10.0,
        help="Per-teacher enrichment timeout in seconds",
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    schools_payload: list[dict[str, object]] = []
    teachers_payload: list[dict[str, object]] = []

    entries = load_school_entries()
    for entry in entries:
        school_id = str(entry.get("id") or "").strip()
        if not school_id:
            continue

        catalog = build_catalog(
            CONFIG_PATH,
            school_filter=school_id,
            limit=None,
            cache_dir=Path(args.cache_dir),
            refresh=args.refresh,
            log_progress=not args.quiet,
            teacher_timeout_seconds=args.teacher_timeout,
        )

        shard_path = output_dir / f"{school_id}.json"
        write_catalog(catalog, shard_path)

        for school in catalog.schools:
            school_dump = school.model_dump(mode="json")
            if school_dump["id"] not in {item["id"] for item in schools_payload}:
                schools_payload.append(school_dump)

        teachers_payload.extend([teacher.model_dump(mode="json") for teacher in catalog.teachers])

        print(json.dumps({"school": school_id, "output": str(shard_path), "teachers": len(catalog.teachers)}, ensure_ascii=False))

    merged_catalog = {
        "generated_at": __import__("datetime").datetime.now().astimezone().isoformat(),
        "note": "Merged from per-school shards generated by crawl_all_schools.py",
        "schools": schools_payload,
        "teachers": teachers_payload,
    }
    live_output = Path(args.live_output)
    live_output.parent.mkdir(parents=True, exist_ok=True)
    live_output.write_text(json.dumps(merged_catalog, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"live_output": str(live_output), "schools": len(schools_payload), "teachers": len(teachers_payload)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
